### ISSUE TITLE
problem : installation of triqs 1.2

### ISSUE THREAD

**Issue by FrankLechermann** [TRIQS/triqs#651]
Hi there,

am trying to install triqs 1.2. Managed to run 'cmake' with all dependencies, but when trying 'make', 
I get the following error message output :

-bash-4.2$ make
[  0%] Built target py_copy
[  1%] Generating gf_wrap.cpp, ../../../include/pytriqs/converters/gf.hpp
Traceback (most recent call last):
  File "/gpfs/.../triqs-1.2/build/pytriqs/gf/local/gf_desc.py", line 368, in <module>
    g = make_gf(py_type = "GfImFreq", c_tag = "imfreq", is_im = True)
  File "/gpfs/.../triqs-1.2/build/pytriqs/gf/local/gf_desc.py", line 314, in make_gf
    g.add_pure_python_method("pytriqs.gf.local._gf_common.LazyCTX", rename = "__lazy_expr_eval_context__")
  File "/gpfs/.../triqs-1.2/build/pytriqs/c++2py/wrap_generator.py", line 542, in add_pure_python_method
    m = __import__(module.rsplit('.')[-1])
  File "/gpfs/.../triqs-1.2/build/pytriqs/gf/local/_gf_common.py", line 22, in <module>
    import numpy
ImportError: No module named numpy
make[2]: *** [pytriqs/gf/local/gf_wrap.cpp] Fehler 1
make[1]: *** [pytriqs/gf/local/CMakeFiles/python_wrap_gf.dir/all] Fehler 2
make: *** [all] Fehler 2

Hence compiling immediately crashes, due to some problem in finding the numpy module. Yet loading numpy within the shell just works fine, so the path is correctly set there. Looks like a problem of how the module (path) is handled in the above routines. Asked various people who installed triqs on other machines and no one encountered a similar error, or found an easy solution to this. 
Am using python-2.7.15 which, together with all the other libraries attached to it, is the only useful one on the given machine.
Perhaps one of the developers has a clue what is going wrong here?

Best, Frank

**Comment by the-hampel** [comment]
Hi Frank,
I do not know about specialties concerning version 1.2, but I know from our clusters that sometimes environment variables are tricky. Do you have the output from the cmake command. From triqs 1.4 I know there is a part where it prints out the numpy version found. Something like this:

```
-- -------- Python detection -------------
-- Python interpreter /apps/monch/p504/triqs-1.4/environment/Python-2.7.12/bin/python
-- Python interpreter and modules are ok : version 2.7.12
-- PYTHON_INCLUDE_DIRS =  /apps/monch/p504/triqs-1.4/environment/Python-2.7.12/include/python2.7
-- PYTHON_H5PY_HDF5VERSION = 1.8.17
-- PYTHON_NUMPY_INCLUDE_DIR = /apps/monch/p504/triqs-1.4/environment/Python-2.7.12/site-packages/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include
-- PYTHON_NUMPY_VERSION = 1.11.2
-- PYTHON_SITE_PKG = /apps/monch/p504/triqs-1.4/environment/Python-2.7.12/lib/python2.7/site-packages
-- PYTHON_LIBRARY = /apps/monch/p504/triqs-1.4/environment/Python-2.7.12/lib/python2.7/config/libpython2.7.a
-- PYTHON_EXTRA_LIBS =-lpthread -ldl  -lutil
-- IPython NOT FOUND 
-- --------------------------------------------
-- Numpy include in /apps/monch/p504/triqs-1.4/environment/Python-2.7.12/site-packages/lib/python2.7/site-packages/numpy-1.11.2-py2.7-linux-x86_64.egg/numpy/core/include
-- Python modules will be installed in /apps/monch/p504/triqs-1.4/triqs.install/lib/python2.7/site-packages/pytriqs
-- Preparing the various scripts 
```
Does this look good while cmake runs? Same python version that you have while executing python from the bash command line? If not you should check the bash environment variables `PYTHONUSERBASE` and `PYTHONPATH`. Are those set to some path that ends with site-packages? And in this folder there should be a numpy version like in my cmake output above. 

If the cmake output is completely different I apologize. I never tried 1.2 ... 

Best,
Alex

**Comment by FrankLechermann** [comment]
Hi Alex,

thanks for your quick reply. 
Yes, I get a very similar output as yours from cmake, all the paths look fine and the python version within the shell is the same as the one that is used in cmake. 
Yet when I print sys.path within the problematic .py file, I recover much "less" paths as when I do it within my shell. It seems that the makefile restricts the paths (and misses also the one for numpy, which is there from the shell command) for some reason which is not clear to me.
Either I made a very very stupid mistake or ...?

Best, Frank

**Comment by FrankLechermann** [comment]
Here is my cmake output for the python detection

-- -------- Python detection -------------
-- Python interpreter /gpfs/software/juwels/stages/2018b/software/Python/2.7.15-GCCcore-8.2.0/bin/python
-- Python interpreter and modules are ok : version 2.7.15
-- PYTHON_INCLUDE_DIRS =  /gpfs/software/juwels/stages/2018b/software/Python/2.7.15-GCCcore-8.2.0/include/python2.7
-- PYTHON_NUMPY_INCLUDE_DIR = /gpfs/software/juwels/stages/2018b/software/SciPy-Stack/2018b-gcccoremkl-8.2.0-2019.0.117-Python-2.7.15/lib/python2.7/site-packages/numpy-1.15.2-py2.7-linux-x86_64.egg/numpy/core/include
-- PYTHON_NUMPY_VERSION = 1.15.2
-- PYTHON_SITE_PKG = /gpfs/software/juwels/stages/2018b/software/Python/2.7.15-GCCcore-8.2.0/lib/python2.7/site-packages
-- PYTHON_LIBRARY = /gpfs/software/juwels/stages/2018b/software/Python/2.7.15-GCCcore-8.2.0/lib/python2.7/config/libpython2.7.a
-- PYTHON_EXTRA_LIBS =/gpfs/software/juwels/stages/2018b/software/libreadline/7.0-GCCcore-8.2.0/lib/libreadline.a /gpfs/software/juwels/stages/2018b/software/ncurses/6.1-GCCcore-8.2.0/lib/libncurses.a -ldl -lm -lpthread -lutil
-- IPython found
-- --------------------------------------------
-- Numpy include in /gpfs/software/juwels/stages/2018b/software/SciPy-Stack/2018b-gcccoremkl-8.2.0-2019.0.117-Python-2.7.15/lib/python2.7/site-packages/numpy-1.15.2-py2.7-linux-x86_64.egg/numpy/core/include
-- Python modules will be installed in /gpfs/homec/hhh08/hhh080/software/lib/python2.7/site-packages/pytriqs
-- Preparing the various scripts

**Comment by the-hampel** [comment]
It might be nothing but your python interpreter path is slightly different from your numpy include dir:
python. Are those two different python version, although they are named so similar? 
python interpreter:
```
.../software/Python/2.7.15-GCCcore-8.2.0/bin/python
```
and numpy include dir:
```
.../software/SciPy-Stack/2018b-gcccoremkl-8.2.0-2019.0.117-Python-2.7.15/lib/python2.7/site-packages/numpy-1.15.2-py2.7-linux-x86_64.egg/numpy/core/include
```
You see the difference? This could cause some trouble. Because I see they both have a site-package folder. Is there a python interpreter in 
```
.../software/juwels/stages/2018b/software/SciPy-Stack/2018b-gcccoremkl-8.2.0-2019.0.117-Python-2.7.15/bin/python
```
? If so one should this one. If this is not the cause, I have no clue what could give make other env variables than cmake...

**Comment by FrankLechermann** [comment]
Yes thanks, I see that the paths are different, but there is no additional interpreter in the path you mention. Hmm, and I thought since cmake identifies all these paths (even if they are "more different"
than in your case) correctly, the resulting makefile should care of all this properly(?)

**Comment by FrankLechermann** [comment]
Checked things again and do not see how it can be done here differently..., thats just how the administrators of the cluster installed python and numpy. There are no other python or numpy versions installed to replace the present setting that cmake detects.

**Comment by HugoStrand** [comment]
Dear Frank,

I think you have hit the same problem as I had some time ago (in 2015). The problem is that we are running Python inside the cmake scripts to generate the wrapper source code. Since cmake changes all the environment paths (including `PYTHON_PATH`) one gets into trouble on systems with Python modules  installed in locations separate from the main Python installation. The solution is to explicitly supply the `PYTHON_PATH` when calling python inside cmake.

I submitted a patch in the issue #177 but I am not sure if it is applicable to `triqs 1.2`.

Best, Hugo

**Comment by parcollet** [comment]
Ok, do I understand that the issue is fixed in current stable ?

**Comment by HugoStrand** [comment]
Yes, @parcollet you fixed it in 3bc4e4a and a15ad71.

**Comment by FrankLechermann** [comment]
Dear Hugo,

thanks a lot! And sorry, I missed this previous comment from 2015. 
After this fix, am still having problems to accomplish the compilation (right now a HDF5 dependence which seems missing at around 14% of compilation), but hopefully I can solve this together with the guys from the supercomputing cluster.

Best, Frank

**Comment by HugoStrand** [comment]
Dear Frank, thank you for reporting back. If you can not solve the `hdf5` issue please reopen this issue and we'll try to help out. Cheers, Hugo
